MODEL:
  TYPE: swin
  NAME: swin_small_rf_adjust
  DROP_PATH_RATE: 0.3
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
    IN_CHANS: 1 #将通道数3改为1

# EnergyToTensor(normalization='mean',augment=False) 
TAG: mean #输出文件夹名称
DATA:
  DATASET: rf

SAVE_FREQ: 4 #每训练5轮保存一次
TRAIN:
  EPOCHS: 80
  WARMUP_EPOCHS: 5
  # WEIGHT_DECAY: 0.05
  # BASE_LR: 1.25e-4
  # WARMUP_LR: 1.25e-7
  # MIN_LR: 1.25e-6
SNR:
  VAL_DB: 8